concourse: Fix typo in self-update get resource name
- This failed to apply:

```
error: invalid pipeline config:
invalid jobs:
	jobs.update-pipeline.plan[0].get.govuk-coronavirus-business-volunteer-people-form refers to a resource that does not exist
```